image: golang:1.23.4

stages:
  - test

unit_test:
  stage: test
  script:
    - go test -v -tags=gorm,x ./...
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
