run:
  allow-parallel-runners: true
  build-tags:
    - gorm
    - x

linters:
  disable-all: true
  enable:
    - gofmt
    - gosec
    - revive
    - gocritic
    - sloglint
    - misspell
    - tparallel
    - unconvert
    - asasalint
    - usestdlibvars
    - gocheckcompilerdirectives 

issues:
  uniq-by-line: false
  exclude-rules:
    - linters:
        - revive
      text: "line-length-limit"
      source: '^\s*\w+\s=\s"[^""]+"|"[^""]{70,}"'
    - path: _test\.go
      linters:
        - gosec
        - gocritic
        - sloglint
        - typecheck
        - unconvert
        - asasalint
        - usestdlibvars
        - gocheckcompilerdirectives 
    - path: examples
      linters:
        - revive
    - path-except: _test\.go
      linters:
        - tparallel

linters-settings:
  gosec:
    exclude-generated: true
    excludes:
      - G101
      - G401
      - G402
      - G501
      - G505
  usestdlibvars:
    time-month: true
    time-layout: true
    crypto-hash: true
    default-rpc-path: true
    sql-isolation-level: true
    tls-signature-scheme: true
    constant-kind: true
  asasalint:
    ignore-test: true
  revive:
    severity: warning
    errorCode: 1
    confidence: 0.8
    warningCode: 0
    ignore-generated-header: true
    rules:
      - name: add-constant
        exclude: ["**_test.go"]
        arguments:
          - maxLitCount: "3"
            allowStrs: '""'
            allowInts: "0,1,2"
            allowFloats: "0.0,0.,1.0,1.,2.0,2."
      - name: argument-limit
      - name: atomic
      - name: banned-characters
      - name: bare-return
      - name: call-to-gc
      - name: comment-spacings
      - name: confusing-naming
      - name: confusing-results
      - name: context-as-argument
      - name: context-keys-type
      - name: cyclomatic
        exclude: ["**_test.go"]
        arguments:
          - 20
        severity: error
      - name: datarace
      - name: deep-exit
      - name: defer
      - name: dot-imports
      - name: early-return
        arguments:
          - "preserveScope"
          - "allowJump"
      - name: empty-block
      - name: empty-lines
      - name: enforce-repeated-arg-type-style
        exclude: ["**_test.go"]
        arguments:
          - "short"
      - name: enforce-slice-style
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      - name: flag-parameter
      - name: identical-branches
      - name: if-return
      - name: import-shadowing
      - name: imports-blocklist
      - name: increment-decrement
      - name: indent-error-flow
      - name: line-length-limit
        exclude: ["**_test.go"]
        severity: warning
      - name: modifies-parameter
      - name: optimize-operands-order
      - name: package-comments
        severity: error
      - name: range-val-address
      - name: range-val-in-closure
      - name: range
      - name: redundant-import-alias
      - name: redundant-build-tag
      - name: redundant-test-main-exit
      - name: string-of-int
      - name: superfluous-else
        arguments:
          - "preserveScope"
      - name: time-equal
      - name: time-naming
      - name: unchecked-type-assertion
        exclude: ["**_test.go"]
        arguments:
          - acceptIgnoredAssertionResult: true
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unexported-return
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unused-parameter
      - name: unused-receiver
      - name: use-any
      - name: use-errors-new
      - name: useless-break
      - name: var-naming
      - name: waitgroup-by-value
